### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Grawp** [dcowden/cadquery#203]
Is Python 3 ever going to be supported?

**Comment by jmwright** [comment]
There's some discussion going on about this in #162 

We're not philosophically opposed to Python 3 support, it just hasn't happened yet. It's a little bit of an unknown quantity to @dcowden and I too, which doesn't help.

**Comment by fragmuffin** [comment]
It's probably a good idea to support it, 3 has some advantages, but ultimately python3 support will have to happen at some point, so it's definitely better to introduce it earlier rather than later.

I've previously set up a testing suite for py2 / py3, so I could make a PR to at least make py3 testing easier.

I've got generally less time over the next few weeks, but I'll try to allocate some time to make a PR.

**Comment by dcowden** [comment]
What version of python does FreeCAD bundle?  I think a good time to switch is when they switch.

**Comment by jmwright** [comment]
Both 0.16 and 0.17 show Python 2.7.12 on my Ubuntu system, but I think FreeCAD uses the system Python version in Linux.

On Windows with 0.16 r6706 the python version is 2.7.8.

**Comment by adam-urbanczyk** [comment]
I just found out that there is FreeCAD conda package with py3.6 for windows and linux:

https://anaconda.org/freecad/freecad/files

If it works properly we can support python3 easily. I will test this once I have some time.

**Comment by jmwright** [comment]
Awesome, that will be very helpful.

**Comment by jmwright** [comment]
Thanks to the work of @adam-urbanczyk and a few other community members, we now have CI integration for Python 3 testing, and all the tests pass.
