### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by RustyVermeer** [dcowden/cadquery#221]
@dcowden @jmwright I've made a documentation update branch with some changes to the docs and the repo's README.
It is, of course, just my suggestion, and doesn't need to necessarily be accepted.

The changes:

- re-organized the repo's readme somewhat so that the flow of information is a bit more consistent. 
- replaced parametricparts.com references with the mybinder Juptyer Notebook link. NOTE: this is ONLY because from what I can tell parametricparts.com no longer serves as CQ execution environment. Jupyter notebooks with the cqnb module essentially replicate that idea though. If this is not ok, let me know!
- very minor tweaks as I was reading through things.

What probably still needs some work:
- the installation instructions page
- perhaps it is time to split the community provided example projects to a new repo? This way people could submit PRs with their examples directly. It might encourage more sharing and take some work off your plates. Eventually, the examples would clutter up the README too much anyway, so I think coming up with some way to handle project sharing would be good.

Link to [the branch](https://github.com/dcowden/cadquery/tree/docs_update)

**Comment by jmwright** [comment]
> replaced parametricparts.com references with the mybinder Juptyer Notebook link. 

+1  I was going to suggest it anyway.

> perhaps it is time to split the community provided example projects to a new repo? 

Until CQGI, most of the examples lived in the FreeCAD module, which was awkward. I think it was a step forward to move them into the main CQ repo. Breaking them out into their own repo is an interesting idea, but will that be easier than letting people submit a PR to this main repo? Is the issue that the examples get lost in this repo so people don't know about them or don't feel comfortable contributing?

**Comment by RustyVermeer** [comment]
I guess it's a bit forward thinking, is all. 

As I was working on the README, I was trying to put the most important info near the top. So, how the user could actually try and use CQ.

The examples fill the README up quite a bit and could be problematic as more come in, as people might not scroll all the way through to read any other important info. 

I don't think it's a pressing thing now, so no need to act on it yet.

**Comment by dcowden** [comment]
One benefit of having a separate examples repo is that it can have its own readme-- that's the benefit contemplated here, I think.  There's no argument that we should move examples off the main readme and onto somewhere else.

Another benefit of a separate examples repo for user-contributed examples is that if they are broken or run a long time, cq development is not held up while they get fixed ( because ideally, we don't release cq with broken examples).  I think this is the strongest argument for another repo for user-contributed examples.


I prefer that examples be done in a way that they are rendered from the code, like in the [documentation](http://dcowden.github.io/cadquery/examples.html).  We've caught problems numerous times that would have otherwise gone undetected.  

With the above in mind, one problem with moving the examples to another repo means that repo would need to install cq in order to execute the examples. That would require the examples to use published versions of cq, which has some advantages and some disadvantages. Either way, it would be some work.

I'd suggest for now that we create a contrib folder, and put user-contributed examples there.  This will be simplest, and gives a way for us to NOT run those as a part of the build, and would allow us all to be somewhat more liberal with accepting PRs for that folder.

**Comment by RustyVermeer** [comment]
@dcowden @jmwright , should  I make a PR for this, or does it perhaps need some further work / editing?

Willing to do whatever is the better workflow on this.

**Comment by jmwright** [comment]
@RustyVermeer My vote would be to go ahead and create a PR so we can start a threaded discussion here about it.

**Comment by jmwright** [comment]
@RustyVermeer I just updated the coverage badge at the top of the readme yesterday, so when you create your PR you'll probably see that conflict right away.
Updated line:
```
[![Coverage Status](https://coveralls.io/repos/github/dcowden/cadquery/badge.svg?branch=master)](https://coveralls.io/github/dcowden/cadquery?branch=master)
```
I think that's the only change since you forked the documentation, but I could be missing something.

**Comment by RustyVermeer** [comment]
closing this as the PR has been accepted.
