### ISSUE TITLE
add ruled argument to loft

### ISSUE THREAD

**Issue by hyOzd** [dcowden/cadquery#90]
Can you add `ruled` argument to `loft()` function? It allows creating loft with straight edges, instead of a smooth surface.

This is the shape I want to create:
![loft_ruled](https://cloud.githubusercontent.com/assets/1479166/8028007/a33097d0-0dac-11e5-8458-186a69a23d8a.png)

Without ruled argument it will look like this :(
![loft_notruled](https://cloud.githubusercontent.com/assets/1479166/8028013/b6807846-0dac-11e5-991e-d1e97b0a589b.png)

This looks like a simple change to me. I already added ruled argument to `FreeCADPart.makeLoft()` call and it worked. I can do a pull request if you agree.

**Comment by jmwright** [comment]
@hyOzd I think that will work fine to add a Ruled argument. The only thing I would suggest is to have it default to False at the [Shell.makeLoft level](https://github.com/dcowden/cadquery/blob/17250d9e1c48e04427af42e9570781e84256509e/cadquery/freecad_impl/shapes.py#L619) so that existing scripts will act as they did before.

**Comment by jmwright** [comment]
Merged
